Grand.Web/Areas/Admin/Controllers/WidgetController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Grand.Web.Areas.Admin.Extensions;
using Grand.Web.Areas.Admin.Models.Cms;
using Grand.Core.Domain.Cms;
using Grand.Core.Plugins;
using Grand.Services.Cms;
using Grand.Services.Configuration;
using Grand.Services.Security;
using Grand.Framework.Kendoui;
using Grand.Framework.Mvc;
using Grand.Core.Caching;

namespace Grand.Web.Areas.Admin.Controllers
{
    public partial class WidgetController : BaseAdminController
	{
		#region Fields

        private readonly IWidgetService _widgetService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly WidgetSettings _widgetSettings;
	    private readonly IPluginFinder _pluginFinder;
        private readonly ICacheManager _cacheManager;
        #endregion

        #region Constructors

        public WidgetController(IWidgetService widgetService,
            IPermissionService permissionService, ISettingService settingService,
            WidgetSettings widgetSettings, IPluginFinder pluginFinder,
            ICacheManager cacheManager)
		{
            this._widgetService = widgetService;
            this._permissionService = permissionService;
            this._settingService = settingService;
            this._widgetSettings = widgetSettings;
            this._pluginFinder = pluginFinder;
            this._cacheManager = cacheManager;

        }

		#endregion 
        
        #region Methods
        
        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            return View();
        }

        [HttpPost]
        public IActionResult List(DataSourceRequest command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var widgetsModel = new List<WidgetModel>();
            var widgets = _widgetService.LoadAllWidgets();
            foreach (var widget in widgets)
            {
                var tmp1 = widget.ToModel();
                tmp1.IsActive = widget.IsWidgetActive(_widgetSettings);
                tmp1.ConfigurationUrl = widget.PluginDescriptor.Instance().GetConfigurationPageUrl();
                tmp1.ConfigurationUrl = widget.GetConfigurationPageUrl();
                widgetsModel.Add(tmp1);
            }
            widgetsModel = widgetsModel.ToList();
            var gridModel = new DataSourceResult
            {
                Data = widgetsModel,
                Total = widgetsModel.Count()
            };

            return Json(gridModel);
        }

        [HttpPost]
        public IActionResult WidgetUpdate( WidgetModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var widget = _widgetService.LoadWidgetBySystemName(model.SystemName);
            if (widget.IsWidgetActive(_widgetSettings))
            {
                if (!model.IsActive)
                {
                    //mark as disabled
                    _widgetSettings.ActiveWidgetSystemNames.Remove(widget.PluginDescriptor.SystemName);
                    _settingService.SaveSetting(_widgetSettings);
                }
            }
            else
            {
                if (model.IsActive)
                {
                    //mark as active
                    _widgetSettings.ActiveWidgetSystemNames.Add(widget.PluginDescriptor.SystemName);
                    _settingService.SaveSetting(_widgetSettings);
                }
            }
            _cacheManager.Clear();
            var pluginDescriptor = widget.PluginDescriptor;
            //display order
            pluginDescriptor.DisplayOrder = model.DisplayOrder;
            PluginFileParser.SavePluginDescriptionFile(pluginDescriptor);
            //reset plugin cache
            _pluginFinder.ReloadPlugins();

            return new NullJsonResult();
        }
        
        public IActionResult ConfigureWidget(string systemName)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var widget = _widgetService.LoadWidgetBySystemName(systemName);
            if (widget == null)
                //No widget found with the specified id
                return RedirectToAction("List");

            var model = widget.ToModel();
            model.ConfigurationUrl = widget.GetConfigurationPageUrl();

            return View(model);
        }

        #endregion
    }
}

Grand.Web/Areas/Admin/Views/Widget/ConfigureWidget.cshtml
@model WidgetModel
@{    
    //page title
    ViewBag.Title = T("Admin.ContentManagement.Widgets.Configure").Text + " - " + Model.FriendlyName;
}
<div class="row">
    <div class="col-md-12">
        <div class="portlet light form-fit">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-tasks"></i>
                    @T("Admin.ContentManagement.Widgets.Configure") - @Model.FriendlyName 
                    <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.ContentManagement.Widgets.BackToList").Text, "List")</small>
                </div>
            </div>
            <div class="portlet-body form">
                <div class="form-horizontal">
                    <div class="form-body">
                        <div class="portlet-body">
                            @if (!String.IsNullOrEmpty(Model.ConfigurationActionName))
                            {
                                @Html.Action(Model.ConfigurationActionName, Model.ConfigurationControllerName, Model.ConfigurationRouteValues);
                            }
                            else
                            {
                                @T("Admin.Common.ConfigurationNotRequired")
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Grand.Web/Areas/Admin/Views/Widget/List.cshtml
@{
    //page title
    ViewBag.Title = T("Admin.ContentManagement.Widgets").Text;
}
@Html.AntiForgeryToken()

<div class="row">
    <div class="col-md-12">
        <div class="portlet light form-fit">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-tasks"></i>
                    @T("Admin.ContentManagement.Widgets")
                </div>
            </div>
            <div class="portlet-body form">
                <div class="form-horizontal">
                    <div class="form-body">
                        <div class="portlet-body">
                            <div id="widgets-grid"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $("#widgets-grid").kendoGrid({
            dataSource: {
                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("List", "Widget"))",
                        type: "POST",
                        dataType: "json",
                        data: addAntiForgeryToken
                    },
                    update: {
                        url: "@Html.Raw(Url.Action("WidgetUpdate", "Widget"))",
                        type: "POST",
                        dataType: "json",
                        data: addAntiForgeryToken
                    }
                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors",
                    model: {
                        id: "SystemName",
                        fields: {
                            FriendlyName: { editable: false, type: "string" },
                            SystemName: { editable: false, type: "string" },
                            DisplayOrder: { editable: true, type: "number" },
                            IsActive: { editable: true, type: "boolean" }
                        }
                    }
                },
                requestEnd: function (e) {
                    if (e.type == "update") {
                        this.read();
                    }
                },
                error: function (e) {
                    display_kendoui_grid_error(e);
                    // Cancel the changes
                    this.cancelChanges();
                },
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            },
            pageable: {
                refresh: true,
                numeric: false,
                previousNext: false,
                info: false
            },
            editable: {
                confirmation: false,
                mode: "inline"
            },
            scrollable: false,
            columns: [{
                field: "FriendlyName",
                title: "@T("Admin.ContentManagement.Widgets.Fields.FriendlyName")",
                width: 250
            }, {
                field: "SystemName",
                title: "@T("Admin.ContentManagement.Widgets.Fields.SystemName")",
                width: 250
            }, {
                field: "DisplayOrder",
                title: "@T("Admin.ContentManagement.Widgets.Fields.DisplayOrder")",
                //integer format
                format: "{0:0}",
                width: 100
            }, {
                field: "IsActive",
                title: "@T("Admin.ContentManagement.Widgets.Fields.IsActive")",
                width: 100,
                headerAttributes: { style: "text-align:center" },
                attributes: { style: "text-align:center" },
                template: '# if(IsActive) {# <i class="fa fa-check" aria-hidden="true" style="color:green"></i> #} else {# <i class="fa fa-times" aria-hidden="true" style="color:red"></i> #} #'
            }, {
                field: "SystemName",
                title: "@T("Admin.ContentManagement.Widgets.Configure")",
                width: 150,
                template: '<a href="#=ConfigurationUrl#">@T("Admin.ContentManagement.Widgets.Configure")</a>'
            }, {
                command: {
                    name: "edit",
                    text: {
                        edit: "@T("Admin.Common.Edit")",
                        update: "@T("Admin.Common.Update")",
                        cancel: "@T("Admin.Common.Cancel")"
                    }
                },
                title: "@T("Admin.Common.Edit")",
                width: 150
            }]
        });
    });
</script>