Grand.Web/Areas/Admin/Models/Stores/StoreModel.cs
using Grand.Framework.Mvc.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Grand.Framework.Mvc.ModelBinding;
using System.Collections.Generic;

using FluentValidation.Attributes;
using Grand.Web.Areas.Admin.Validators.Stores;
using Grand.Framework;
using Grand.Framework.Localization;
using Grand.Framework.Mvc;

namespace Grand.Web.Areas.Admin.Models.Stores
{
    [Validator(typeof(StoreValidator))]
    public partial class StoreModel : BaseGrandEntityModel, ILocalizedModel<StoreLocalizedModel>
    {
        public StoreModel()
        {
            Locales = new List<StoreLocalizedModel>();
            AvailableLanguages = new List<SelectListItem>();
            AvailableWarehouses = new List<SelectListItem>();
        }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.Name")]
        
        public string Name { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.Url")]
        
        public string Url { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.SslEnabled")]
        public virtual bool SslEnabled { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.SecureUrl")]
        
        public virtual string SecureUrl { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.Hosts")]
        
        public string Hosts { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.DisplayOrder")]
        public int DisplayOrder { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.CompanyName")]
        
        public string CompanyName { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.CompanyAddress")]
        
        public string CompanyAddress { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.CompanyPhoneNumber")]
        
        public string CompanyPhoneNumber { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.CompanyVat")]
        
        public string CompanyVat { get; set; }


        public IList<StoreLocalizedModel> Locales { get; set; }
        //default language
        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.DefaultLanguage")]
        
        public string DefaultLanguageId { get; set; }
        public IList<SelectListItem> AvailableLanguages { get; set; }

        //default warehouse
        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.DefaultWarehouse")]
        
        public string DefaultWarehouseId { get; set; }
        public IList<SelectListItem> AvailableWarehouses { get; set; }

    }

    public partial class StoreLocalizedModel : ILocalizedModelLocal
    {
        public string LanguageId { get; set; }

        [GrandResourceDisplayName("Admin.Configuration.Stores.Fields.Name")]
        
        public string Name { get; set; }
    }
}

Grand.Web/Areas/Admin/Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Grand.Framework.Mvc.Filters;
using System;
using System.Linq;
using Grand.Web.Areas.Admin.Extensions;
using Grand.Web.Areas.Admin.Models.Stores;
using Grand.Core.Domain.Stores;
using Grand.Services.Configuration;
using Grand.Services.Localization;
using Grand.Services.Security;
using Grand.Services.Stores;
using Grand.Framework.Controllers;
using Grand.Framework.Kendoui;
using System.Collections.Generic;
using Grand.Core.Domain.Localization;
using Grand.Services.Shipping;

namespace Grand.Web.Areas.Admin.Controllers
{
    public partial class StoreController : BaseAdminController
    {
        private readonly IStoreService _storeService;
        private readonly ISettingService _settingService;
        private readonly ILanguageService _languageService;
        private readonly ILocalizationService _localizationService;
        private readonly IPermissionService _permissionService;
        private readonly IShippingService _shippingService;

        public StoreController(IStoreService storeService,
            ISettingService settingService,
            ILanguageService languageService,
            ILocalizationService localizationService,
            IPermissionService permissionService,
            IShippingService shippingService)
        {
            this._storeService = storeService;
            this._settingService = settingService;
            this._languageService = languageService;
            this._localizationService = localizationService;
            this._permissionService = permissionService;
            this._shippingService = shippingService;
        }

        [NonAction]
        protected virtual void PrepareLanguagesModel(StoreModel model)
        {
            if (model == null)
                throw new ArgumentNullException("model");

            //templates
            model.AvailableLanguages.Add(new SelectListItem
            {
                Text = "---",
                Value = ""
            });
            var languages = _languageService.GetAllLanguages(true);
            foreach (var language in languages)
            {
                model.AvailableLanguages.Add(new SelectListItem
                {
                    Text = language.Name,
                    Value = language.Id.ToString()
                });
            }
        }
        [NonAction]
        protected virtual void PrepareWarehouseModel(StoreModel model)
        {
            if (model == null)
                throw new ArgumentNullException("model");

            //templates
            model.AvailableWarehouses.Add(new SelectListItem
            {
                Text = "---",
                Value = ""
            });
            var warehouses = _shippingService.GetAllWarehouses();
            foreach (var warehouse in warehouses)
            {
                model.AvailableWarehouses.Add(new SelectListItem
                {
                    Text = warehouse.Name,
                    Value = warehouse.Id.ToString()
                });
            }
        }

        [NonAction]
        protected virtual List<LocalizedProperty> UpdateAttributeLocales(Store store, StoreModel model)
        {
            List<LocalizedProperty> localized = new List<LocalizedProperty>();
            foreach (var local in model.Locales)
            {
                localized.Add(new LocalizedProperty()
                {
                    LanguageId = local.LanguageId,
                    LocaleKey = "Name",
                    LocaleValue = local.Name
                });
            }
            return localized;
        }

        public IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageStores))
                return AccessDeniedView();

            return View();
        }

        [HttpPost]
        public IActionResult List(DataSourceRequest command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageStores))
                return AccessDeniedView();

            var storeModels = _storeService.GetAllStores()
                .Select(x => x.ToModel())
                .ToList();

            var gridModel = new DataSourceResult
            {
                Data = storeModels,
                Total = storeModels.Count()
            };

            return Json(gridModel);
        }

        public IActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageStores))
                return AccessDeniedView();

            var model = new StoreModel();
            //locales
            AddLocales(_languageService, model.Locales);
            //languages
            PrepareLanguagesModel(model);
            //warehouses
            PrepareWarehouseModel(model);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public IActionResult Create(StoreModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageStores))
                return AccessDeniedView();
            
            if (ModelState.IsValid)
            {
                var store = model.ToEntity();
                //ensure we have "/" at the end
                if (!store.Url.EndsWith("/"))
                    store.Url += "/";
                store.Locales = UpdateAttributeLocales(store, model);
                _storeService.InsertStore(store);

                SuccessNotification(_localizationService.GetResource("Admin.Configuration.Stores.Added"));
                return continueEditing ? RedirectToAction("Edit", new { id = store.Id }) : RedirectToAction("List");
            }
            //languages
            PrepareLanguagesModel(model);
            //warehouses
            PrepareWarehouseModel(model);

            //If we got this far, something failed, redisplay form
            return View(model);
        }

        public IActionResult Edit(string id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageStores))
                return AccessDeniedView();

            var store = _storeService.GetStoreById(id);
            if (store == null)
                //No store found with the specified id
                return RedirectToAction("List");

            var model = store.ToModel();
            //languages
            PrepareLanguagesModel(model);
            //warehouses
            PrepareWarehouseModel(model);
            //locales
            AddLocales(_languageService, model.Locales, (locale, languageId) =>
            {
                locale.Name = store.GetLocalized(x => x.Name, languageId, false, false);
            });
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        public IActionResult Edit(StoreModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageStores))
                return AccessDeniedView();

            var store = _storeService.GetStoreById(model.Id);
            if (store == null)
                //No store found with the specified id
                return RedirectToAction("List");
            
            if (ModelState.IsValid)
            {
                store = model.ToEntity(store);
                //ensure we have "/" at the end
                if (!store.Url.EndsWith("/"))
                    store.Url += "/";

                store.Locales = UpdateAttributeLocales(store, model);
                _storeService.UpdateStore(store);
                //locales

                SuccessNotification(_localizationService.GetResource("Admin.Configuration.Stores.Updated"));
                return continueEditing ? RedirectToAction("Edit", new { id = store.Id }) : RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            //languages
            PrepareLanguagesModel(model);
            //warehouses
            PrepareWarehouseModel(model);

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(string id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageStores))
                return AccessDeniedView();

            var store = _storeService.GetStoreById(id);
            if (store == null)
                //No store found with the specified id
                return RedirectToAction("List");

            try
            {
                _storeService.DeleteStore(store);

                //when we delete a store we should also ensure that all "per store" settings will also be deleted
                var settingsToDelete = _settingService
                    .GetAllSettings()
                    .Where(s => s.StoreId == id)
                    .ToList();
                foreach (var setting in settingsToDelete)
                    _settingService.DeleteSetting(setting);
                //when we had two stores and now have only one store, we also should delete all "per store" settings
                var allStores = _storeService.GetAllStores();
                if (allStores.Count == 1)
                {
                    settingsToDelete = _settingService
                        .GetAllSettings()
                        .Where(s => s.StoreId == allStores[0].Id)
                        .ToList();
                    foreach (var setting in settingsToDelete)
                        _settingService.DeleteSetting(setting);
                }


                SuccessNotification(_localizationService.GetResource("Admin.Configuration.Stores.Deleted"));
                return RedirectToAction("List");
            }
            catch (Exception exc)
            {

Grand.Web/Areas/Admin/Views/Store/Create.cshtml
@model StoreModel
@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Stores.AddNew").Text;
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light form-fit">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-shopping-cart"></i>
                        @T("Admin.Configuration.Stores.AddNew") 
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.Configuration.Stores.BackToList").Text, "List") </small>
                    </div>
                    <div class="actions">
                        <div class="btn-group btn-group-devided">
                            <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @T("Admin.Common.Save") </button>
                            <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @T("Admin.Common.SaveContinue") </button>                            
                        </div>
                    </div>
                </div>
                <div class="portlet-body form">
                    @Html.Partial("_CreateOrUpdate", Model)
                </div>
            </div>
        </div>
    </div>


}

Grand.Web/Areas/Admin/Views/Store/Edit.cshtml
@model StoreModel
@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Stores.EditStoreDetails").Text;
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light form-fit">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-shopping-cart"></i>
                        @T("Admin.Configuration.Stores.EditStoreDetails") - @Model.Name 
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.Configuration.Stores.BackToList").Text, "List") </small>
                    </div>
                    <div class="actions">
                        <div class="btn-group btn-group-devided">
                            <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @T("Admin.Common.Save") </button>
                            <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @T("Admin.Common.SaveContinue") </button>
                            <span id="store-delete" class="btn red"><i class="fa fa-trash-o"></i> @T("Admin.Common.Delete")</span>
                        </div>
                    </div>
                </div>
                <div class="portlet-body form">
                    @Html.Partial("_CreateOrUpdate", Model)
                </div>
            </div>
        </div>
    </div>


}
@Html.DeleteConfirmation("store-delete")

Grand.Web/Areas/Admin/Views/Store/List.cshtml
@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Stores").Text;
}
@Html.AntiForgeryToken()
<div class="row">
    <div class="col-md-12">
        <div class="portlet light form-fit">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-shopping-cart"></i>
                    @T("Admin.Configuration.Stores")
                </div>
                <div class="actions btn-group btn-group-devided">
                    <a href="@Url.Action("Create")" class="btn green"><i class="fa fa-plus"></i><span class="hidden-xs"> @T("Admin.Common.AddNew") </span></a>
                </div>
            </div>
            <div class="portlet-body form">
                <div class="form-horizontal">
                    <div class="form-body">
                        <div class="portlet-body">
                            <div id="stores-grid"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


    <script>
        $(document).ready(function () {
            $("#stores-grid").kendoGrid({
                dataSource: {
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("List", "Store"))",
                            type: "POST",
                            dataType: "json",
                            data: addAntiForgeryToken
                        }
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors"
                    },
                    error: function(e) {
                        display_kendoui_grid_error(e);
                        // Cancel the changes
                        this.cancelChanges();
                    },
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                pageable: {
                    refresh: true,
                    numeric: false,
                    previousNext: false,
                    info: false
                },
                editable: {
                    confirmation: false,
                    mode: "inline"
                },
                scrollable: false,
                columns: [{
                    field: "Name",
                    title: "@T("Admin.Configuration.Stores.Fields.Name")"
                }, {
                    field: "Url",
                    title: "@T("Admin.Configuration.Stores.Fields.Url")"
                }, {
                    field: "DisplayOrder",
                    title: "@T("Admin.Configuration.Stores.Fields.DisplayOrder")"
                }, {
                    field: "Id",
                    title: "@T("Admin.Common.Edit")",
                    width: 100,
                    template: '<a class="btn btn-sm btn-default" href="Edit/#=Id#"><i class="fa fa-pencil"></i> @T("Admin.Common.Edit")</a>'
                }]
            });
        });
    </script>

Grand.Web/Areas/Admin/Views/Store/_CreateOrUpdate.cshtml
@model StoreModel

@Html.ValidationSummary(true)
@Html.HiddenFor(model => model.Id)

<script type="text/javascript">
    $(document).ready(function () {

        $("#@Html.FieldIdFor(model => model.SslEnabled)").click(toggleSslEnabled);

        toggleSslEnabled();
    });

    function toggleSslEnabled() {
        if ($('#@Html.FieldIdFor(model => model.SslEnabled)').is(':checked')) {
            $('#pnlSecureUrl').show();
        }
        else {
            $('#pnlSecureUrl').hide();
        }
    }
</script>
@(Html.LocalizedEditor<StoreModel, StoreLocalizedModel>("store-localized",
    @<div class="form-horizontal">
         <div class="form-body">
             <div class="form-group">
                     @Html.GrandLabelFor(model => model.Locales[item].Name)
                 <div class="col-md-9 col-sm-9">
                     @Html.GrandEditorFor(model => model.Locales[item].Name)
                     @Html.ValidationMessageFor(model => model.Locales[item].Name)
                 </div>
             </div>
            @Html.HiddenFor(model => model.Locales[item].LanguageId)
         </div>
    </div>
    ,
    @<div class="form-horizontal">
         <div class="form-body">
             <div class="form-group">
                     @Html.GrandLabelFor(model => model.Name)
                 <div class="col-md-9 col-sm-9">
                     @Html.GrandEditorFor(model => model.Name)
                     @Html.ValidationMessageFor(model => model.Name)
                 </div>
             </div>
         </div>
    </div>
))
<div class="form-horizontal">
    <div class="form-body">
        <div class="form-group">
                @Html.GrandLabelFor(model => model.Url)
            <div class="col-md-9 col-sm-9">
                @Html.GrandEditorFor(model => model.Url)
                @Html.ValidationMessageFor(model => model.Url)
            </div>
        </div>
        <div class="form-group">
                @Html.GrandLabelFor(model => model.SslEnabled)
            <div class="col-md-9 col-sm-9">
                <label class="mt-checkbox mt-checkbox-outline">
                    @Html.GrandEditorFor(model => model.SslEnabled)
                    <span></span>
                </label>
                @Html.ValidationMessageFor(model => model.SslEnabled)
            </div>
        </div>
        <div class="form-group">
            <div class="note note-info">
                <em>@T("Admin.Configuration.Stores.Fields.SslEnabled.Hint2")</em>
            </div>
        </div>
        <div class="form-group" id="pnlSecureUrl">            
                @Html.GrandLabelFor(model => model.SecureUrl)
            <div class="col-md-9 col-sm-9">
                @Html.GrandEditorFor(model => model.SecureUrl)
                @Html.ValidationMessageFor(model => model.SecureUrl)
            </div>
        </div>
        <div class="form-group">
                @Html.GrandLabelFor(model => model.Hosts)
            <div class="col-md-9 col-sm-9">
                @Html.GrandEditorFor(model => model.Hosts)
                @Html.ValidationMessageFor(model => model.Hosts)
            </div>
        </div>
        <div class="form-group">
                @Html.GrandLabelFor(model => model.DefaultLanguageId)
            <div class="col-md-9 col-sm-9">
                @Html.GrandDropDownListFor(model => model.DefaultLanguageId, Model.AvailableLanguages)
                @Html.ValidationMessageFor(model => model.DefaultLanguageId)
            </div>
        </div>
        <div class="form-group">
                @Html.GrandLabelFor(model => model.DisplayOrder)
            <div class="col-md-9 col-sm-9">
                @Html.GrandEditorFor(model => model.DisplayOrder)
                @Html.ValidationMessageFor(model => model.DisplayOrder)
            </div>
        </div>
        <div class="form-group">
                @Html.GrandLabelFor(model => model.CompanyName)
            <div class="col-md-9 col-sm-9">
                @Html.GrandEditorFor(model => model.CompanyName)
                @Html.ValidationMessageFor(model => model.CompanyName)
            </div>
        </div>
        <div class="form-group">
                @Html.GrandLabelFor(model => model.CompanyAddress)
            <div class="col-md-9 col-sm-9">
                @Html.GrandEditorFor(model => model.CompanyAddress)
                @Html.ValidationMessageFor(model => model.CompanyAddress)
            </div>
        </div>
        <div class="form-group">
                @Html.GrandLabelFor(model => model.CompanyPhoneNumber)
            <div class="col-md-9 col-sm-9">
                @Html.GrandEditorFor(model => model.CompanyPhoneNumber)
                @Html.ValidationMessageFor(model => model.CompanyPhoneNumber)
            </div>
        </div>
        <div class="form-group">
                @Html.GrandLabelFor(model => model.CompanyVat)
            <div class="col-md-9 col-sm-9">
                @Html.GrandEditorFor(model => model.CompanyVat)
                @Html.ValidationMessageFor(model => model.CompanyVat)
            </div>
        </div>
        <div class="form-group">
            @Html.GrandLabelFor(model => model.DefaultWarehouseId)
            <div class="col-md-9 col-sm-9">
                @Html.GrandDropDownListFor(model => model.DefaultWarehouseId, Model.AvailableWarehouses)
                @Html.ValidationMessageFor(model => model.DefaultWarehouseId)
            </div>
        </div>
    </div>
</div>